### ISSUE TITLE
Loading

### ISSUE THREAD

**Issue by klondike-enjoyer** [kalilistic/klondike#16]
klondike seems to just say Loading, while all other parse overlays work as intended.

**Comment by kalilistic** [comment]
Are you using ACT? Nothing has changed with the overlay in years so shouldn't be on the klondike side.

**Comment by eliu12** [comment]
Can confirm, the most recent ACT update seemed to have broken klondike. It hasn't been working for me and everyone I know who uses that overlay.

**Comment by kalilistic** [comment]
Ah, I see the details of the error in the ACT discord. I made an announcement issue. Thanks for reporting.
https://github.com/kalilistic/klondike/issues/17
