### ISSUE TITLE
add PCT/VPR as dps

### ISSUE THREAD

**Issue by KyelerO** [kalilistic/klondike#19]
pwetty pwease make pct and vpr dps and not just random gray bars

**Comment by kalilistic** [comment]
Hey, it's already been updated. Are you using [kalilistic.github.io/klondike](https://kalilistic.github.io/klondike)?

**Comment by KyelerO** [comment]
oooh no i think i was using a diff one when we were having issues a few weeks ago. Removed and re-added and its there now ty <3
