### ISSUE TITLE
[Request] Death count in overlay

### ISSUE THREAD

**Issue by JStav** [kalilistic/klondike#5]
Hello! I hope it is okay for me to open this issue. 

Loving the overlay! It would be awesome if there was a death count somewhere on the overlay.

**Comment by kalilistic** [comment]
Hey, glad you like it. There is the death count if you click on someone's name. Or do you mean on the overlay itself?

**Comment by JStav** [comment]
Ooh! I did not notice the death count when clicking a person's name. That is good to know.

Having it on the overlay itself would be nice as well but I realize the design for klondike is minimalist so I understand why it is not there.

**Comment by kalilistic** [comment]
Glad it helps. I'm a little torn on adding some new fields but as you said... going for a minimalist style for this. If I add new fields I'd need to start adding labels/column headings and might get busy quickly.

**Comment by JStav** [comment]
That's understandable, thanks for considering it!

**Comment by kalilistic** [comment]
@JStav Added a secondary stat option under Player Details including deaths! 👍

**Comment by JStav** [comment]
I see the option! This is amazing, thank you. Will definitely test out next raid night.
